### ISSUE TITLE
Issue visualizing candidate library

### ISSUE THREAD

**Issue by sparktx-ariel-hippen** [bowang-lab/AGILE#6]
I am trying to use `infer_viz.py` to visualize how the 12,000 candidate lipids perform in the finetuned model. To do this, I am using the following steps:

1. Run fine-tuning on the existing data, aka run `python finetune.py config_finetune.yaml` with no edits to config_finetune.yaml. This creates a directory called `finetune/Sep25_15-12-09_lnp_hela_with_feat_expt_Hela`
2. Change the task in the yaml file created in `finetune/Sep25_15-12-09_lnp_hela_with_feat_expt_Hela/checkpoints/config_finetune.yaml` to `task_name: smiles12000_with_feat`.
3. Run `python infer_viz.py Sep25_15-12-09_lnp_hela_with_feat_expt_Hela`.

On step 3, I get the following output:
```/home/ubuntu/miniconda3/envs/agile/lib/python3.9/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/ubuntu/miniconda3/envs/agile/lib/python3.9/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/ubuntu/miniconda3/envs/agile/lib/python3.9/site-packages/umap/distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/ubuntu/miniconda3/envs/agile/lib/python3.9/site-packages/umap/umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
Please install apex for mixed precision training from: https://github.com/NVIDIA/apex
Running on: cuda:0
12276
/home/ubuntu/miniconda3/envs/agile/lib/python3.9/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
AGILE(
  (x_embedding1): Embedding(119, 300)
  (x_embedding2): Embedding(3, 300)
  (gnns): ModuleList(
    (0): GINEConv()
    (1): GINEConv()
    (2): GINEConv()
    (3): GINEConv()
    (4): GINEConv()
  )
  (batch_norms): ModuleList(
    (0): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (4): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (feat_lin): Linear(in_features=300, out_features=512, bias=True)
  (pred_feat): Sequential(
    (0): Linear(in_features=813, out_features=100, bias=True)
    (1): ELU(alpha=1.0)
    (2): LayerNorm((100,), eps=1e-05, elementwise_affine=True)
  )
  (pred_head): Sequential(
    (0): Linear(in_features=612, out_features=256, bias=True)
    (1): Softplus(beta=1, threshold=20)
    (2): Linear(in_features=256, out_features=256, bias=True)
    (3): Softplus(beta=1, threshold=20)
    (4): Linear(in_features=256, out_features=1, bias=True)
  )
)
Loaded pre-trained model with success.
pred_feat.0.weight True
pred_feat.0.bias True
pred_feat.2.weight True
pred_feat.2.bias True
pred_head.0.weight True
pred_head.0.bias True
pred_head.2.weight True
pred_head.2.bias True
pred_head.4.weight True
pred_head.4.bias True
Test loss: 7.473151369955611 Test RMSE: 2.7337065 Test Corr: -0.11244599739893202
Traceback (most recent call last):
  File "/mnt/bfx-ops/users/ariel/agile_test/infer_viz.py", line 669, in <module>
    fig = infer_agent.visualize(embs, predictions=pred, color_key="predictions")
  File "/mnt/bfx-ops/users/ariel/agile_test/infer_viz.py", line 484, in visualize
    embedding = reducer.fit_transform(embeddings)
  File "/home/ubuntu/miniconda3/envs/agile/lib/python3.9/site-packages/umap/umap_.py", line 2772, in fit_transform
    self.fit(X, y)
  File "/home/ubuntu/miniconda3/envs/agile/lib/python3.9/site-packages/umap/umap_.py", line 2516, in fit
    ) = nearest_neighbors(
  File "/home/ubuntu/miniconda3/envs/agile/lib/python3.9/site-packages/umap/umap_.py", line 342, in nearest_neighbors
    knn_indices, knn_dists = knn_search_index.neighbor_graph
  File "/home/ubuntu/miniconda3/envs/agile/lib/python3.9/site-packages/pynndescent/pynndescent_.py", line 1615, in neighbor_graph
    self._distance_correction(self._neighbor_graph[1]),
  File "/home/ubuntu/miniconda3/envs/agile/lib/python3.9/site-packages/numba/np/ufunc/dufunc.py", line 190, in __call__
    return super().__call__(*args, **kws)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'correct_alternative_cosine' did not contain a loop with signature matching types <class 'numpy.dtype[float32]'> -> None
```

As far as I can tell, the inference step is being performed properly, but putting the embeddings in UMAP space for visualization is failing. Any advice about how to avoid this error is appreciated. 

For reference, I am running this in a conda environment created using the exact commands included in the Installation included in the README, with the exception that I replaced numpy==1.26.1 with numpy==1.22 to avoid an error with calling numba.

**Comment by rexxxx1234** [comment]
Hi @sparktx-ariel-hippen, thanks for the question and hope you have resolved the problem already! If not, I believe this is an issue somewhere in the interactions of numba, numpy. You can check out this GitHub issue: https://github.com/lmcinnes/pynndescent/issues/163.

**Comment by sparktx-ariel-hippen** [comment]
The solution you pointed me to worked, thank you!
